baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Test Blog'
theme = 'hugo-flex'

[[menu.nav]]
name = "About"
url = "about/"
weight = 1

[[menu.nav]]
name = "Posts"
url = "post/"
weight = 2

[[menu.nav]]
name = "Tags"
url = "tags/"
weight = 3

[[menu.nav]]
name = "Categories"
url = "categories/"
weight = 4